//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BOSSreader
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BossDataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BossDataContext object using the connection string found in the 'BossDataContext' section of the application configuration file.
        /// </summary>
        public BossDataContext() : base("name=BossDataContext", "BossDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BossDataContext object.
        /// </summary>
        public BossDataContext(string connectionString) : base(connectionString, "BossDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BossDataContext object.
        /// </summary>
        public BossDataContext(EntityConnection connection) : base(connection, "BossDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BossRangeData> BossRangeDatas
        {
            get
            {
                if ((_BossRangeDatas == null))
                {
                    _BossRangeDatas = base.CreateObjectSet<BossRangeData>("BossRangeDatas");
                }
                return _BossRangeDatas;
            }
        }
        private ObjectSet<BossRangeData> _BossRangeDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Record> Records
        {
            get
            {
                if ((_Records == null))
                {
                    _Records = base.CreateObjectSet<Record>("Records");
                }
                return _Records;
            }
        }
        private ObjectSet<Record> _Records;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DailyView> DailyViews
        {
            get
            {
                if ((_DailyViews == null))
                {
                    _DailyViews = base.CreateObjectSet<DailyView>("DailyViews");
                }
                return _DailyViews;
            }
        }
        private ObjectSet<DailyView> _DailyViews;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BossRangeDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBossRangeDatas(BossRangeData bossRangeData)
        {
            base.AddObject("BossRangeDatas", bossRangeData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Records EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecords(Record record)
        {
            base.AddObject("Records", record);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DailyViews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDailyViews(DailyView dailyView)
        {
            base.AddObject("DailyViews", dailyView);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BossRecordsData", Name="BossRangeData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BossRangeData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BossRangeData object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BossRangeData CreateBossRangeData(global::System.Int32 id)
        {
            BossRangeData bossRangeData = new BossRangeData();
            bossRangeData.ID = id;
            return bossRangeData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Specification
        {
            get
            {
                return _Specification;
            }
            set
            {
                OnSpecificationChanging(value);
                ReportPropertyChanging("Specification");
                _Specification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Specification");
                OnSpecificationChanged();
            }
        }
        private global::System.String _Specification;
        partial void OnSpecificationChanging(global::System.String value);
        partial void OnSpecificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RangeLow
        {
            get
            {
                return _RangeLow;
            }
            set
            {
                OnRangeLowChanging(value);
                ReportPropertyChanging("RangeLow");
                _RangeLow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RangeLow");
                OnRangeLowChanged();
            }
        }
        private Nullable<global::System.Int32> _RangeLow;
        partial void OnRangeLowChanging(Nullable<global::System.Int32> value);
        partial void OnRangeLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RangeHigh
        {
            get
            {
                return _RangeHigh;
            }
            set
            {
                OnRangeHighChanging(value);
                ReportPropertyChanging("RangeHigh");
                _RangeHigh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RangeHigh");
                OnRangeHighChanged();
            }
        }
        private Nullable<global::System.Int32> _RangeHigh;
        partial void OnRangeHighChanging(Nullable<global::System.Int32> value);
        partial void OnRangeHighChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BossRecordsData", Name="DailyView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DailyView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DailyView object.
        /// </summary>
        /// <param name="product">Initial value of the Product property.</param>
        public static DailyView CreateDailyView(global::System.String product)
        {
            DailyView dailyView = new DailyView();
            dailyView.Product = product;
            return dailyView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                if (_Product != value)
                {
                    OnProductChanging(value);
                    ReportPropertyChanging("Product");
                    _Product = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Product");
                    OnProductChanged();
                }
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BHNCount
        {
            get
            {
                return _BHNCount;
            }
            set
            {
                OnBHNCountChanging(value);
                ReportPropertyChanging("BHNCount");
                _BHNCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BHNCount");
                OnBHNCountChanged();
            }
        }
        private Nullable<global::System.Int32> _BHNCount;
        partial void OnBHNCountChanging(Nullable<global::System.Int32> value);
        partial void OnBHNCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Minimum
        {
            get
            {
                return _Minimum;
            }
            set
            {
                OnMinimumChanging(value);
                ReportPropertyChanging("Minimum");
                _Minimum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Minimum");
                OnMinimumChanged();
            }
        }
        private Nullable<global::System.Double> _Minimum;
        partial void OnMinimumChanging(Nullable<global::System.Double> value);
        partial void OnMinimumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Max
        {
            get
            {
                return _Max;
            }
            set
            {
                OnMaxChanging(value);
                ReportPropertyChanging("Max");
                _Max = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Max");
                OnMaxChanged();
            }
        }
        private Nullable<global::System.Double> _Max;
        partial void OnMaxChanging(Nullable<global::System.Double> value);
        partial void OnMaxChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BossRecordsData", Name="Record")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Record : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Record object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="bHNReading">Initial value of the BHNReading property.</param>
        /// <param name="product">Initial value of the Product property.</param>
        public static Record CreateRecord(global::System.Int32 id, global::System.DateTime date, global::System.Double bHNReading, global::System.String product)
        {
            Record record = new Record();
            record.ID = id;
            record.Date = date;
            record.BHNReading = bHNReading;
            record.Product = product;
            return record;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double BHNReading
        {
            get
            {
                return _BHNReading;
            }
            set
            {
                OnBHNReadingChanging(value);
                ReportPropertyChanging("BHNReading");
                _BHNReading = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BHNReading");
                OnBHNReadingChanged();
            }
        }
        private global::System.Double _BHNReading;
        partial void OnBHNReadingChanging(global::System.Double value);
        partial void OnBHNReadingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CastDate
        {
            get
            {
                return _CastDate;
            }
            set
            {
                OnCastDateChanging(value);
                ReportPropertyChanging("CastDate");
                _CastDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CastDate");
                OnCastDateChanged();
            }
        }
        private global::System.String _CastDate;
        partial void OnCastDateChanging(global::System.String value);
        partial void OnCastDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCast
        {
            get
            {
                return _DateCast;
            }
            set
            {
                OnDateCastChanging(value);
                ReportPropertyChanging("DateCast");
                _DateCast = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCast");
                OnDateCastChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCast;
        partial void OnDateCastChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCastChanged();

        #endregion

    
    }

    #endregion

    
}
